config/routes.rb
Rails.application.routes.draw do
  resources :akshays
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/akshay.rb
class Akshay < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/akshays_controller.rb
class AkshaysController < ApplicationController
  before_action :set_akshay, only: %i[ show edit update destroy ]

  # GET /akshays or /akshays.json
  def index
    @akshays = Akshay.all
  end

  # GET /akshays/1 or /akshays/1.json
  def show
  end

  # GET /akshays/new
  def new
    @akshay = Akshay.new
  end

  # GET /akshays/1/edit
  def edit
  end

  # POST /akshays or /akshays.json
  def create
    @akshay = Akshay.new(akshay_params)

    respond_to do |format|
      if @akshay.save
        format.html { redirect_to akshay_url(@akshay), notice: "Akshay was successfully created." }
        format.json { render :show, status: :created, location: @akshay }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @akshay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /akshays/1 or /akshays/1.json
  def update
    respond_to do |format|
      if @akshay.update(akshay_params)
        format.html { redirect_to akshay_url(@akshay), notice: "Akshay was successfully updated." }
        format.json { render :show, status: :ok, location: @akshay }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @akshay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akshays/1 or /akshays/1.json
  def destroy
    @akshay.destroy

    respond_to do |format|
      format.html { redirect_to akshays_url, notice: "Akshay was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_akshay
      @akshay = Akshay.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def akshay_params
      params.require(:akshay).permit(:name, :age)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/akshays_helper.rb
module AkshaysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/akshays/_form.html.erb
<%= form_with(model: akshay) do |form| %>
  <% if akshay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(akshay.errors.count, "error") %> prohibited this akshay from being saved:</h2>

      <ul>
        <% akshay.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/akshays/edit.html.erb
<h1>Editing Akshay</h1>

<%= render 'form', akshay: @akshay %>

<%= link_to 'Show', @akshay %> |
<%= link_to 'Back', akshays_path %>

app/views/akshays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Akshays</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @akshays.each do |akshay| %>
      <tr>
        <td><%= akshay.name %></td>
        <td><%= akshay.age %></td>
        <td><%= link_to 'Show', akshay %></td>
        <td><%= link_to 'Edit', edit_akshay_path(akshay) %></td>
        <td><%= link_to 'Destroy', akshay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Akshay', new_akshay_path %>

app/views/akshays/new.html.erb
<h1>New Akshay</h1>

<%= render 'form', akshay: @akshay %>

<%= link_to 'Back', akshays_path %>

app/views/akshays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @akshay.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @akshay.age %>
</p>

<%= link_to 'Edit', edit_akshay_path(@akshay) %> |
<%= link_to 'Back', akshays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mahesh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>